Only start download, if there is a different version then installed
ansiblebit/oracle-java pull request #102
Opened 2018-11-12 16:08 UTC by peshay

I added to the main tasks: `when: oracle_java_version_installed != oracle_java_version_string` 
So the download/installation would only start if the installed version does not matches the intended version. 
I also had some Warnings  in Ansible, so I fixed them all. 

May I also suggest to add a task that find the lastest Update version of a JDK release? So this could then automatically fill in things like `oracle_java_rpm_filename`, `oracle_java_rpm_url`, `oracle_java_version_string` depending on which `oracle_java_version` is set.

2018-11-14 14:50 UTC, peshay commented
I also added a new default value for RedHat `oracle_java_latest`, if changed to `oracle_java_latest: true` the `find_latest.yml` will be included in order to overwrite `oracle_java_rpm_filename`, `oracle_java_rpm_url`, `oracle_java_update_string` (only for jdk8, e.g. 192), `oracle_java_version_string`

2018-11-15 22:56 UTC, steenzout commented
@peshay this role used to have the logic to get the latest version only for this logic to get deprecated and stop working as it should.

I really appreciate the PR but I'm not keen in merging this logic to this role again.

if you want to do a new PR up to [99025d176c11cc72c72f442c36831d88dc2bfb2](
https://github.com/ansiblebit/oracle-java/pull/102/commits/99025d176c11cc72c72f442c36831d88dc2bfb2), I'll merge asap.

2018-11-15 22:57 UTC, steenzout requested changes
+1 for all commits up to `99025d176c11cc72c72f442c36831d88dc2bfb2`

2018-11-16 11:11 UTC, closed without merging

2018-11-16 11:16 UTC, peshay commented
I separate the change in a new Pull Request. Regarding downloading latest version of jdk for RedHat RPM:
As far as I understood the role, currently it will get the latest for Debian systems, but only the one defined version in the defaults for RedHat. Wouldn't it be better to have the same behaviour for both distributions?
If the role should still work like it's working now, then my change wouldn't change that, because if someone wants the new behaviour to get the latest JDK update version, he could change `oracle_java_latest` to `true`